name: Docker Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build & Push to repository
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ghcr.io/muhammadsuryono/academic-api-service
      TAGS: ${GITHUB_REF##*/}
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - name: Build and Push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "muhammadsuryono" --password-stdin
          docker image build -t ${{ env.IMG_NAME }}:${{ env.TAGS }}-v2 .
          docker push ${{ env.IMG_NAME }}:${{ env.TAGS }}-v2
